apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xdatabases.database.bedag.ch
spec:
  group: database.bedag.ch
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: Database
    plural: databases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              dbru:
                type: integer
                maximum: 20
              dbinstance:
                type: string
            required: 
              - name
              - dbru
              - dbinstance
