apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-http
  namespace: argocd
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://bedag.github.io/helm-charts/
    targetRevision: 2.0.0
    chart: raw
    helm:
      valuesObject:
        resources:
          - apiVersion: pkg.crossplane.io/v1beta1
            kind: DeploymentRuntimeConfig
            metadata:
              name: provider-http
              annotations:
                argocd.argoproj.io/sync-wave: "0"
            spec:
              serviceAccountTemplate:
                metadata:
                  name: provider-http
          - apiVersion: pkg.crossplane.io/v1
            kind: Provider
            metadata:
              name: provider-http
              annotations:
                argocd.argoproj.io/sync-wave: "1"
            spec:
              package: xpkg.upbound.io/crossplane-contrib/provider-http:v1.0.8
              runtimeConfigRef:
                apiVersion: pkg.crossplane.io/v1beta1
                kind: DeploymentRuntimeConfig
                name: provider-http
          - apiVersion: http.crossplane.io/v1alpha1
            kind: ProviderConfig
            metadata:
              name: http-conf
              annotations:
                argocd.argoproj.io/sync-wave: "2"
                argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
            spec:
              credentials:
                source: None
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
