apiVersion: v1
kind: Pod
metadata:
  labels:
    run: postgres
  name: postgres
  namespace: default
spec:
  containers:
  - env:
    - name: POSTGRES_PASSWORD
      value: pass
    image: postgres
    name: postgres
    ports:
    - containerPort: 5432
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: postgres
  type: LoadBalancer

