apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbinstances.database.bedag.ch
spec:
  group: database.bedag.ch
  scope: Cluster
  names:
    plural: dbinstances
    singular: dbinstance
    kind: DBInstance
    shortNames:
      - dbi
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                Name:
                  type: string
                DBRU:
                  type: integer
                  maximum: 30
                Networkcontext:
                  type: string
                ServiceLevel:
                  type: string
                  enum:
                    - Platin
                    - Bronze
              required:
                - Name
                - DBRU
                - Networkcontext
                - ServiceLevel
      additionalPrinterColumns:
      - name: Name
        type: string
        description: The name of the DB instance
        jsonPath: .spec.Name
      - name: DBRU
        type: integer
        description: The number of database resource units (DBRU)
        jsonPath: .spec.DBRU
      - name: Networkcontext
        type: string
        description: The network context of the DB instance
        jsonPath: .spec.Networkcontext
      - name: ServiceLevel
        type: string
        description: The service level of the DB instance
        jsonPath: .spec.ServiceLevel